### ISSUE TITLE
can't run dns2proxy.py

### ISSUE THREAD

**Issue by Alextrrz** [LeonardoNve/dns2proxy#10]
Hi I'm trying to run dns2proxy.py and get an error
python dns2proxy.py
  File "dns2proxy.py", line 175
    print str
            ^
SyntaxError: Missing parentheses in call to 'print'
Yes...I'm trying to run it on an android terminal, hope I don't look that noob, till now Sslstrip2 has worked fine :)

**Comment by LeonardoNve** [comment]
I have not tried it in Android, which Python version did you use? Try with 2.7
