### ISSUE TITLE
dns2proxy alongside dnsmasq

### ISSUE THREAD

**Issue by nirlandau** [LeonardoNve/dns2proxy#11]
Hi,
I was using dnsmasq for dhcp and dns services.
Now, in order to use dns2proxy I need to disable the dns feature of dnsmasq (obviously because they both use port 53). 
I do that by setting port=0 in the conf file (as explained in the documents).
After making sure that the dns feature is not working I tried using dns2proxy but for some reason it didn’t get any requests from a connected device (it did get requests from localhost).
Only after turning off dnsmasq completely (including the dhcp), it got the requests.
This is not good for me because I must keep the dhcp on.

Any reasons why it is this way?

(I’ve read on other forums that turning off dnsmasq completely helps, but I do need its dhcp...)

**Comment by LeonardoNve** [comment]
I´m not sure, use `netstat -lunp` before run dns2proxy to be sure the 53/udp is free.

Leonardo.

**Comment by nirlandau** [comment]
i did check and it is free

**Comment by nirlandau** [comment]
I found the problem!
In the dnsmasq.conf file. the interface was set to a specific one.
After removing that, everything works perfectly.

Thank you
