### ISSUE TITLE
Error while using dns2proxy ImportError: No module named pcapy.

### ISSUE THREAD

**Issue by maxet007** [LeonardoNve/dns2proxy#12]
I downloaded dns2proxy, but when i write **python dns2proxy.py** in dns2proxy-master folder i have this error: 

> root@kali:/home/maxet/dns2proxy-master# python dns2proxy.py
Traceback (most recent call last):
  File "dns2proxy.py", line 29, in <module>
    import pcapy
ImportError: No module named pcapy

So, i tried to install pcapy by **sudo pip install pcapy** but i have another error: 

> root@kali:/home/maxet/dns2proxy-master# sudo pip install pcapy
/usr/share/python-wheels/pkg_resources-0.0.0-py3-none-any.whl/pkg_resources/py2_warn.py:21: UserWarning: Setuptools will stop working on Python 2
You are running Setuptools on Python 2, which is no longer
supported and
SETUPTOOLS WILL STOP WORKING <<<
in a subsequent release (no sooner than 2020-04-20).
Please ensure you are installing
Setuptools using pip 9.x or later or pin to `setuptools<45`
in your environment.
If you have done those things and are still encountering
this message, please follow up at
(link).
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support                                          
Collecting pcapy
  Using cached pcapy-0.11.4.tar.gz (37 kB)
Building wheels for collected packages: pcapy
  Building wheel for pcapy (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-utTKtw/pcapy/setup.py'"'"'; __file__='"'"'/tmp/pip-install-utTKtw/pcapy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-GnpDDF                                                              
       cwd: /tmp/pip-install-utTKtw/pcapy/                                 
  Complete output (6 lines):                                               
  usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]    
     or: setup.py --help [cmd1 cmd2 ...]                                   
     or: setup.py --help-commands                                          
     or: setup.py cmd --help                                               
  error: invalid command 'bdist_wheel'                                     
  ERROR: Failed building wheel for pcapy
  Running setup.py clean for pcapy
Failed to build pcapy
Installing collected packages: pcapy
    Running setup.py install for pcapy ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-utTKtw/pcapy/setup.py'"'"'; __file__='"'"'/tmp/pip-install-utTKtw/pcapy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-zWnW2k/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python2.7/pcapy              
         cwd: /tmp/pip-install-utTKtw/pcapy/                               
    Complete output (12 lines):                                            
    running install                                                        
    running build                                                          
    running build_ext                                                      
    building 'pcapy' extension                                             
    creating build                                                         
    creating build/temp.linux-x86_64-2.7                                   
    x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-uC7NI8/python2.7-2.7.18=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c pcapdumper.cc -o build/temp.linux-x86_64-2.7/pcapdumper.o                                                                          
    pcapdumper.cc:11:10: fatal error: pcap.h: Нет такого файла или каталога
       11 | #include <pcap.h>                                              
          |          ^~~~~~~~                                              
    compilation terminated.                                                
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1        
ERROR: Command errored out with exit status 1: /usr/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-utTKtw/pcapy/setup.py'"'"'; __file__='"'"'/tmp/pip-install-utTKtw/pcapy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-zWnW2k/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python2.7/pcapy Check the logs for full command output.                
root@kali:/home/maxet/dns2proxy-master#

**Comment by LeonardoNve** [comment]
It seems that it is an error when you install pcapy , not an error on dns2proxy.

try first `pip install wheel ` and after that try to install pcapy.

**Comment by maxet007** [comment]
> It seems that it is an error when you install pcapy , not an error on dns2proxy.
> 
> try first `pip install wheel ` and after that try to install pcapy.

Thank you for answer, but it's not working:

> maxet@kali:~$ pip install wheel
/usr/share/python-wheels/pkg_resources-0.0.0-py3-none-any.whl/pkg_resources/py2_warn.py:21: UserWarning: Setuptools will stop working on Python 2
You are running Setuptools on Python 2, which is no longer
supported and
SETUPTOOLS WILL STOP WORKING 
in a subsequent release (no sooner than 2020-04-20).
Please ensure you are installing
Setuptools using pip 9.x or later or pin to `setuptools<45`
in your environment.
If you have done those things and are still encountering
this message, please follow up at
(link)
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support                                          
Collecting wheel
  Downloading wheel-0.34.2-py2.py3-none-any.whl (26 kB)
Installing collected packages: wheel
  WARNING: The script wheel is installed in '/home/maxet/.local/bin' which is not on PATH.                                                            
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.                                   
Successfully installed wheel-0.34.2

>maxet@kali:$ pip install pcapy
/usr/share/python-wheels/pkg_resources-0.0.0-py3-none-any.whl/pkg_resources/py2_warn.py:21: UserWarning: Setuptools will stop working on Python 2
You are running Setuptools on Python 2, which is no longer
supported and
SETUPTOOLS WILL STOP WORKING 
in a subsequent release (no sooner than 2020-04-20).
Please ensure you are installing
Setuptools using pip 9.x or later or pin to `setuptools<45`
in your environment.
If you have done those things and are still encountering
this message, please follow up at
(link)
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support                                          
Collecting pcapy
  Downloading pcapy-0.11.4.tar.gz (37 kB)
Building wheels for collected packages: pcapy
  Building wheel for pcapy (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-h1A_cE/pcapy/setup.py'"'"'; __file__='"'"'/tmp/pip-install-h1A_cE/pcapy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-uqgBOz                                                              
       cwd: /tmp/pip-install-h1A_cE/pcapy/                                 
  Complete output (12 lines):                                              
  running bdist_wheel                                                      
  running build                                                            
  running build_ext                                                        
  building 'pcapy' extension                                               
  creating build                                                           
  creating build/temp.linux-x86_64-2.7                                     
  x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-uC7NI8/python2.7-2.7.18=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c pcapdumper.cc -o build/temp.linux-x86_64-2.7/pcapdumper.o 
  pcapdumper.cc:11:10: fatal error: pcap.h: Нет такого файла или каталога  
     11 | #include <pcap.h>                                                
        |          ^~~~~~~~                                                
  compilation terminated.                                                  
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1                                     
  ERROR: Failed building wheel for pcapy
  Running setup.py clean for pcapy
Failed to build pcapy
Installing collected packages: pcapy
    Running setup.py install for pcapy ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-h1A_cE/pcapy/setup.py'"'"'; __file__='"'"'/tmp/pip-install-h1A_cE/pcapy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-GiDFSw/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/maxet/.local/include/python2.7/pcapy                                                                
         cwd: /tmp/pip-install-h1A_cE/pcapy/                               
    Complete output (12 lines):                                            
    running install                                                        
    running build                                                          
    running build_ext                                                      
    building 'pcapy' extension                                             
    creating build                                                         
    creating build/temp.linux-x86_64-2.7                                   
    x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-uC7NI8/python2.7-2.7.18=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c pcapdumper.cc -o build/temp.linux-x86_64-2.7/pcapdumper.o                                                                          
    pcapdumper.cc:11:10: fatal error: pcap.h: Нет такого файла или каталога
       11 | #include <pcap.h>                                              
          |          ^~~~~~~~                                              
    compilation terminated.                                                
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1        
    ----------------------------------------                               
ERROR: Command errored out with exit status 1: /usr/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-h1A_cE/pcapy/setup.py'"'"'; __file__='"'"'/tmp/pip-install-h1A_cE/pcapy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-GiDFSw/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/maxet/.local/include/python2.7/pcapy Check the logs for full command output.

**Comment by maxet007** [comment]
Laso i tried **maxet@kali:~$ sudo pip3 install wheel*:

> maxet@kali:~$ sudo pip3 install wheel
Requirement already satisfied: wheel in /usr/lib/python3/dist-packages (0.34.2)

and **sudo pip3 install pcapy**

> maxet@kali:~$ sudo pip3 install pcapy
Collecting pcapy
  Using cached pcapy-0.11.4.tar.gz (37 kB)
Building wheels for collected packages: pcapy
  Building wheel for pcapy (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ccax16ld/pcapy/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ccax16ld/pcapy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-pyhb85em                                                       
       cwd: /tmp/pip-install-ccax16ld/pcapy/                               
  Complete output (12 lines):                                              
  running bdist_wheel                                                      
  running build                                                            
  running build_ext                                                        
  building 'pcapy' extension                                               
  creating build                                                           
  creating build/temp.linux-x86_64-3.8                                     
  x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.8 -c pcapdumper.cc -o build/temp.linux-x86_64-3.8/pcapdumper.o                   
  pcapdumper.cc:11:10: fatal error: pcap.h: Нет такого файла или каталога  
     11 | #include <pcap.h>                                                
        |          ^~~~~~~~                                                
  compilation terminated.                                                  
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1                                      
  ERROR: Failed building wheel for pcapy
  Running setup.py clean for pcapy
Failed to build pcapy
Installing collected packages: pcapy
    Running setup.py install for pcapy ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ccax16ld/pcapy/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ccax16ld/pcapy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-f7vwl6yy/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.8/pcapy       
         cwd: /tmp/pip-install-ccax16ld/pcapy/                             
    Complete output (12 lines):                                            
    running install                                                        
    running build                                                          
    running build_ext                                                      
    building 'pcapy' extension                                             
    creating build                                                         
    creating build/temp.linux-x86_64-3.8                                   
    x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.8 -c pcapdumper.cc -o build/temp.linux-x86_64-3.8/pcapdumper.o                 
    pcapdumper.cc:11:10: fatal error: pcap.h: Нет такого файла или каталога
       11 | #include <pcap.h>                                              
          |          ^~~~~~~~                                              
    compilation terminated.                                                
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1        
    ----------------------------------------                               
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ccax16ld/pcapy/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ccax16ld/pcapy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-f7vwl6yy/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.8/pcapy Check the logs for full command output.

**Comment by maxet007** [comment]
I think that more convenient to watch:
![Снимок экрана_2020-06-01_18-27-16](https://user-images.githubusercontent.com/36376329/83424899-bda2b380-a435-11ea-98cc-9d4b9d1c4b0e.png)
![Снимок экрана_2020-06-01_18-28-03](https://user-images.githubusercontent.com/36376329/83424901-be3b4a00-a435-11ea-87e7-e7db8d6446a5.png)
Ты не из россии случайно?

**Comment by maxet007** [comment]
Oh i made it! Thank you. I entered **sudo apt install libpcap-dev
**
