### ISSUE TITLE
sslstrip2+ not redirect anything!

### ISSUE THREAD

**Issue by vincenzogianfelice** [LeonardoNve/dns2proxy#14]
Hi, after writing rules (`./sslstrip.py -l 8080`):
```
-A PREROUTING -p tcp -m tcp --dport 80 -j REDIRECT --to-ports 8080
-A PREROUTING -p udp -m udp --dport 53 -j REDIRECT --to-ports 53
```

... and having started the tool **dns2proxy**, **sslstrip2+** not capture anything. Why redirect on port input 80 instedad 443? The connection of input is arrive from 443 (https).

**Comment by kaizerandroid** [comment]
Alguien tiene el archivo actulizado para python 3 ? Ya que pyhton 2.7  no permite utilizarlo

**Comment by LeonardoNve** [comment]
@vincenzogianfelice clearly you don´t understand the attack, you have to intercept HTTP requests....

@kaizerandroid Está programado para 2.7, lo siento, tendrás que utilizarlo así
