### ISSUE TITLE
No host exception

### ISSUE THREAD

**Issue by jcarlos7121** [LeonardoNve/dns2proxy#5]
Hello Leonardo! Saludos!

could you check the changes made from the last commit? i tried to setup up the environment with sslstrip, and when the dns2proxy sent any hostname change like social.facebook.com, it throws a no host exception and the result was a 404.

I tried the version before the last merge and it worked like a charm. can you just verify this last version works?

and one last question.

Does the attack is still been able to be done even when the user previously entered the page as https? for example for the 2nd or 3rd time? the first time the user goes to the page, the dns2proxy makes the hostname change, but if the user entered facebook previously as https, there is no hostname change and the browser sets him on https, just as before.

**Comment by LeonardoNve** [comment]
Hola Juan Carlos!
 I will check it this weekend that error.

For the other question:

This is like de original sslstrip it relays on the fact the target click on a link in a page sender via http (so captured and modified) or in a redirection through http so it doesn't matter if the target visited before that page in https.
